package net.zerobone.grammax.generator.slr;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import net.zerobone.grammax.Grammax;
import net.zerobone.grammax.generator.GeneratorContext;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class SLRGenerator {

    public static void generate(GeneratorContext context) throws IOException {
        {
            TypeSpec parserClass = SLRParserClassGenerator.generate(context).build();

            JavaFile.Builder javaFileBuiler = JavaFile
                .builder(context.packageName, parserClass)
                .indent("    ")
                .skipJavaLangImports(true)
                .addFileComment("This file was generated by Grammax v" + Grammax.VERSION);

            // javaFileBuiler.staticImports.add(context.configuration.imports);

            JavaFile javaFile = javaFileBuiler.build();

            BufferedWriter writer = new BufferedWriter(new FileWriter(context.className + ".java"));
            javaFile.writeTo(writer);
            writer.close();
        }
    }

}