package net.zerobone.grammax.generator.slr;

import net.zerobone.grammax.Grammax;
import net.zerobone.grammax.generator.GeneratorContext;
import net.zerobone.grammax.generator.JavaWriter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class SLRGenerator {

    private static void generateParserClass(GeneratorContext context) throws IOException {

        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(context.configuration.getName() + ".java"));

        JavaWriter writer = new JavaWriter(bufferedWriter);

        writer.write("/* This file was generated by Grammax v");
        writer.write(Grammax.VERSION);
        writer.write(" */");
        writer.newLine();

        writer.writeAlignTrim(context.configuration.topCode);

        writer.newLine();

        // local imports
        writer.write("import java.util.Stack;");

        writer.newLine();
        writer.newLine();

        SLRParserClassGenerator.generate(writer, context);

        writer.close();

    }

    public static void generate(GeneratorContext context) throws IOException {

        generateParserClass(context);

    }

}