package net.zerobone.grammax.generator.lr;

import net.zerobone.grammax.Grammax;
import net.zerobone.grammax.generator.GeneratorContext;
import net.zerobone.grammax.generator.JavaWriter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class LRGenerator {

    private static void generateParserClass(GeneratorContext context) throws IOException {

        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(context.config.getName() + ".java"));

        JavaWriter writer = new JavaWriter(bufferedWriter);

        writer.write("/* This file was generated by Grammax v");
        writer.write(Grammax.VERSION);
        writer.write(" */");
        writer.newLine();

        if (context.config.topCode != null) {
            writer.writeAlignTrim(context.config.topCode);
        }

        writer.newLine();

        // local imports
        writer.write("import java.util.Stack;");

        writer.newLine();
        writer.newLine();

        LRParserClassGenerator.generate(writer, context);

        writer.close();

    }

    public static void generate(GeneratorContext context) throws IOException {

        generateParserClass(context);

    }

}